[package]
name = "countio"
version = "0.1.0"
edition = "2021"

[lib]
path = "./lib.rs"

[features]
default = ["std"]
std = []
futures = ["dep:futures-io"]
tokio = ["dep:tokio"]

[dependencies]
futures-io = { version = "0.3.26", optional = true }
tokio = { version = "1.25.0", optional = true, default-features = false }

[dev-dependencies]
futures-test = { version = "0.3.26" }
tokio = { version = "1.25.0", features = ["rt", "macros"] }
