[package]
name = "countio"
version = "0.1.0"
edition = "2021"

[lib]
path = "./lib.rs"

[features]
std = []
futures = ["dep:futures-io"]
tokio = ["dep:tokio"] # "dep:pin-project-lite"

[dependencies]
futures-io = { version = "0.3.26", optional = true }
tokio = { version = "1.25.0", optional = true, default-features = false }
#pin-project-lite = { version = "0.2.9", optional = true, default-features = false }
